### ISSUE TITLE
java.lang.NullPointerException: Initializing game

### ISSUE THREAD

**Issue by Sailren** [Horeak/MiscItemsAndBlocks-Source-Code#4]
this crash happens during startup: http://paste.ubuntu.com/9682915/

**Comment by tm1990** [comment]
Should be fixed in the newest commit https://github.com/tm1990/MiscItemsAndBlocks-Source-Code/commit/b1538d7c40fe85299610eea44980336d3ebcc732 Will reupload a new version on curseforge in a little bit
